### PR TITLE
chore: add Symfony 7 support

### PR DESCRIPTION
**Pull request by mRoca**
Fixes https://github.com/bpolaszek/webpush-bundle/issues/49

Nothing changed in the src dir, except removing of sf4 dedicated blocs.

I've updated some dev vendors, but `--prefer-lowest` deps are still not usable, especially because of `bentools/doctrine-static` old doctrine requirement (I've added some `Doctrine\Common\Persistence ` old interfaces stubs in order to keep using it).

### CODE REVIEW

**Comment by bpolaszek** [comment]
Very good job @mRoca !
Regarding `bentools/doctrine-static`, there are probably more common / modern ways to tackle Doctrine tests now - we could either use an Sqlite database or just mock Doctrine. 
Do you fancy doing this? If that's too much work, tell me and we'll address this later.

**Comment by mRoca** [comment]
Hi @bpolaszek, I totally agree with you, but it would indeed imply spending too much time for this PR. IMHO, the best option would be using Doctrine with in-memory sqlite db, but it should maybe be the point of another PR.

**Comment by mRoca** [comment]
@bpolaszek I've just added a `WebPushBundle::build: void` in order to avoid the following log:

```
deprecation.INFO: User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "BenTools\WebPushBundle\WebPushBundle" now to avoid errors or add an explicit @return annotation to suppress this message at vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
```

**Comment by rcournault** [comment]
@bpolaszek Why not merge this Pull Request ?

**Review by bpolaszek — APPROVED** [review]

**Comment by bpolaszek** [comment]
Thank you @mRoca ! 🙏

**Comment by rcournault** [comment]
@bpolaszek Thank you ! Can you create a release / version / tag plz ? Can you do a realesed so I can update my project with composer ?

**Pull request merged**
